version: "3.9"
services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./toybox-server/data:/db/conf/
    env_file:
      - ./toybox-server/.env

  api:
    build: ./toybox-server/
    command: pipenv run uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./toybox-server:/api
    ports:
      - "8000:8000"
    env_file:
      - ./toybox-server/.env
    depends_on:
      - db

  nuxt:
    build:
      context: ./ToyBox-frontend/
      args:
        WORKDIR: front
    ports:
      - 3000:3000
    volumes:
      - ./ToyBox-frontend:/front
      - node_modules_volume:/front/node_modules
    working_dir: /front
    env_file:
      - ./ToyBox-frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c 'pwd && ls && yarn install && yarn dev:host'
volumes:
  dbdata: null
  node_modules_volume: null
